//
// Created by junior on 2019/11/7.
//

#ifndef NETWORKS_CPP_CONFIG_H
#define NETWORKS_CPP_CONFIG_H

#define NETWORKS_CPP_VERSION_MAJOR 0
#define NETWORKS_CPP_VERSION_MINOR 0
#define NETWORKS_CPP_VERSION_PATCH 1

#endif //NETWORKS_CPP_CONFIG_H
